# Generated by Django 6.0.5 on 2026-06-09 16:11

import django.db.models.deletion
import django_cryptography.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_bases_app', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=200, verbose_name='ID модели в API')),
                ('display_name', models.CharField(max_length=200, verbose_name='Отображаемое имя')),
                ('context_length', models.IntegerField(default=4096, verbose_name='Длина контекста (токены)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM модель',
                'verbose_name_plural': 'LLM модели',
                'ordering': ['provider', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название провайдера')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Идентификатор')),
                ('base_url', models.URLField(verbose_name='API endpoint')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('supports_streaming', models.BooleanField(default=True, verbose_name='Поддерживает стриминг')),
                ('default_temperature', models.FloatField(default=0.7, verbose_name='Температура по умолчанию')),
                ('default_system_prompt', models.TextField(default='You are a helpful assistant that answers questions based on the provided documentation. Be concise, accurate, and cite sources when possible.', verbose_name='Системный промт по умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM провайдер',
                'verbose_name_plural': 'LLM провайдеры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название чата')),
                ('system_prompt', models.TextField(blank=True, null=True, verbose_name='Системный промт')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Температура')),
                ('top_k', models.IntegerField(default=5, verbose_name='Количество релевантных чанков')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='knowledge_bases_app.knowledgebase', verbose_name='База знаний')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_chats', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('llm_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='llms_app.llmmodel', verbose_name='LLM модель')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='llms_app.llmprovider', verbose_name='Провайдер'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'Ассистент')], max_length=20, verbose_name='Роль')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='llms_app.chat', verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='llmmodel',
            unique_together={('provider', 'model_id')},
        ),
        migrations.CreateModel(
            name='UserAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', django_cryptography.fields.encrypt(models.CharField(max_length=100))),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_keys', to='llms_app.llmprovider', verbose_name='Провайдер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'API ключ пользователя',
                'verbose_name_plural': 'API ключи пользователей',
                'ordering': ['user', 'provider'],
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
