# Generated by Django 6.0.5 on 2026-06-18 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llms_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProviderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Температура')),
                ('system_prompt', models.TextField(blank=True, null=True, verbose_name='Системный промт')),
                ('top_k', models.IntegerField(default=5, verbose_name='Количество чанков')),
                ('similarity_threshold', models.FloatField(default=0.7, verbose_name='Порог сходства')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='llms_app.llmmodel', verbose_name='Модель по умолчанию')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to='llms_app.llmprovider', verbose_name='Провайдер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки провайдера для пользователя',
                'verbose_name_plural': 'Настройки провайдеров для пользователей',
                'ordering': ['user', 'provider'],
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
