# Generated by Django 6.0.5 on 2026-06-08 18:10

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField(verbose_name='Текст чанка')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True, verbose_name='Векторное представление')),
                ('source_url', models.URLField(max_length=2000, verbose_name='URL источника')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Хранит заголовок, индекс чанка, секцию и т.д.', verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Чанк документации',
                'verbose_name_plural': 'Чанки документации',
                'ordering': ['knowledge_base', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('source_url', models.URLField(verbose_name='URL документации')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('parsing', 'Парсинг'), ('ready', 'Готов'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
            ],
            options={
                'verbose_name': 'База знаний',
                'verbose_name_plural': 'Базы знаний',
                'ordering': ['-created_at'],
            },
        ),
    ]
