# Generated by Django 6.0.5 on 2026-06-02 10:40

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_bases_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField(verbose_name='Текст чанка')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True, verbose_name='Векторное представление')),
                ('source_url', models.URLField(max_length=2000, verbose_name='URL источника')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Хранит заголовок, индекс чанка, секцию и т.д.', verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge_bases_app.knowledgebase', verbose_name='База знаний')),
            ],
            options={
                'verbose_name': 'Чанк документации',
                'verbose_name_plural': 'Чанки документации',
                'ordering': ['knowledge_base', 'created_at'],
                'indexes': [models.Index(fields=['knowledge_base'], name='knowledge_b_knowled_8def82_idx')],
            },
        ),
    ]
