# Generated by Django 6.0.5 on 2026-06-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_bases_app', '0002_documentchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке'),
        ),
    ]
